# ---------------- 安装包

# install.packages('utf8')
# install.packages('rJava')
# install.packages('glue')
# install.packages('tidyr')
# install.packages('dplyr')
# install.packages('lubridate')
# install.packages('plyr')
# install.packages('stringr')
# install.packages('readr')
# install.packages('readxl')
# install.packages('openxlsx')
# install.packages('zoo')
# install.packages('car')
# install.packages('RODBC')
# install.packages('RSQLite')
# install.packages('ggplot2')
# install.packages(c('vctrs' , 'httr' , 'rvest'))
# install.packages('xml2')
# install.packages("RJDBC")
# install.packages("DBI")
# install.packages("carData")
# install.packages("xts")
# install.packages("sqldf")
# install.packages("class")
# install.packages("RMySQL")
# install.packages("getopt")
# install.packages("jsonlite")
# install.packages("rlist")
# install.packages("rlang")
# install.packages("tidyselect")

# install_version("mongolite", version = "2.0")  未用到mongo，因此无需安装


# ---------------- 加载包

library('utf8')
library('rJava')
library('DBI')
library('RODBC')
library('RJDBC')
library('sqldf')
library('RSQLite')
library('RMySQL')
library('glue')
library('tidyr')
library('plyr')
library('dplyr')
library('lubridate')
library('stringr')
library('readr')
library('readxl')
library('openxlsx')
library('class')
library('zoo')
library('carData')
library('car')
library('ggplot2')
library('vctrs')
library('httr')
library('xml2')
library('rvest')
library('xts')
library('getopt')
library('jsonlite')
library('rlist')
library('rlang')
library('tidyselect')

print('source package success')
